# -*- dockerfile -*-
# Memcached
#
# VERSION       0.1

# dotCloud image
FROM ubuntu
MAINTAINER Antoine R. Dumont, github.com/ardumont

# Update to the latest packages
RUN echo "deb http://archive.ubuntu.com/ubuntu precise main universe" > /etc/apt/sources.list
RUN apt-get update

# Install memcached
RUN apt-get install -y memcached

# memcached run at container startup
ENTRYPOINT ["memcached"]

# run the container as daemon
USER daemon

# Expose the current port for memcached
EXPOSE 11211
