# -*- dockerfile -*-
# Hey Dude at container startup
#
# VERSION       0.1

# dotCloud image
FROM ubuntu
MAINTAINER Antoine R. Dumont, github.com/ardumont

# Say hello when container starts
ENTRYPOINT echo "Hey Dude!"
