# -*- dockerfile -*-
# Hey Dude at container startup 
#
# VERSION       1.0

# dotCloud image
from ubuntu
MAINTAINER Antoine R. Dumont, ardumont@dotcloud.com

# Say hello when container starts
ENTRYPOINT echo "Hey Dude!"

