# -*- dockerfile -*-
# Jenkins
#
# VERSION       0.1

FROM ubuntu:saucy-oracle-jdk7
MAINTAINER Antoine R. Dumont, github.com/ardumont

# Install JDK
RUN apt-get update
RUN apt-get install -q -y openjdk-7-jre-headless
RUN apt-get install -q -y zip
RUN apt-get install -q -y git
RUN apt-get install -q -y gradle
RUN apt-get clean

# Download Jenkins JAR file
# ADD http://mirrors.jenkins-ci.org/war/1.559/jenkins.war /opt/jenkins.war
ADD http://mirrors.jenkins-ci.org/war/1.532/jenkins.war /opt/jenkins.war
RUN ln -sf /jenkins /root/.jenkins

# Start Jenkins
ENTRYPOINT ["java", "-jar", "/opt/jenkins.war"]

# Expose port 8080
EXPOSE 8080

# Export "/jenkins" mounting point
VOLUME ["/jenkins"]

# Default command is empty
CMD [""]
