# -*- dockerfile -*-
# Jenkins
#
# VERSION       0.1

FROM ubuntu:saucy-openssh
MAINTAINER Antoine R. Dumont, github.com/ardumont

RUN apt-get update && apt-get clean
RUN apt-get install -q -y openjdk-7-jre-headless zip && apt-get clean
ADD http://mirrors.jenkins-ci.org/war/1.559/jenkins.war /opt/jenkins.war
RUN ln -sf /jenkins /root/.jenkins

ENTRYPOINT ["java", "-jar", "/opt/jenkins.war"]
EXPOSE 8080
VOLUME ["/jenkins"]
CMD [""]
