FROM ubuntu:12.04                                                                                                                                                    
                                                                                                                                                                     
RUN apt-get update && apt-get clean                                                                                                                                  
RUN apt-get install -q -y openjdk-7-jre-headless zip && apt-get clean                                                                                                
ADD http://mirrors.jenkins-ci.org/war/1.559/jenkins.war /opt/jenkins.war                                                                                             
RUN ln -sf /jenkins /root/.jenkins                                                                                                                                   
                                                                                                                                                                     
ENTRYPOINT ["java", "-jar", "/opt/jenkins.war"]                                                                                                                      
EXPOSE 8080                                                                                                                                                          
VOLUME ["/jenkins"]                                                                                                                                                  
CMD [""]